### ISSUE TITLE
(P)react component support

### ISSUE THREAD

**Issue by solarispika** [tsl0922/ttyd#659]
**Is your feature request related to a problem? Please describe.**
I found issue https://github.com/tsl0922/ttyd/issues/492 after I finished the following words.
The issue said that being a react library is not intended, but preact version is also an option to me.
Therefore I wonder if that could happen or not.

---
I want to use `App` from `ttyd/html/src/components/app.tsx` in my react project, and put it inside a container instead of using up a page.
Having little knowledge to Node.js/React, I tried to do this by
- webpack'ing `ttyd/html/src/components/app.tsx` into `ttyd/html/dist/ttyd.js`, and
- setting `main` in `package.json` to `./dist/ttyd.js`.
It does produce `./dist/ttyd.js`, but it still doesn't work.
I tried using node to import it, but it failed in loading.

```
Welcome to Node.js v15.13.0.
Type ".help" for more information.
> try { require('./dist/ttyd'); } catch(e) { console.log(e.stack); }
ReferenceError: window is not defined
    at Object.<anonymous> (/ttyd/html/node_modules/xterm-addon-web-links/lib/xterm-addon-web-links.js:1:208)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at eval (webpack:///external_%22xterm-addon-web-links%22?:1:18)
    at Object.xterm-addon-web-links (/ttyd/html/dist/ttyd.js:267:1)
    at __webpack_require__ (/ttyd/html/dist/ttyd.js:20:30)
```

**Describe the solution you'd like**
Something like this.
```javascript
import { App } from 'ttyd';
function MyComp {
    return <App prop1="xxx" />;
}
````

**Describe alternatives you've considered**
None, but not limited to the one mentioned above.

**Additional context**
None.

**Comment by tsl0922** [comment]
Nope. You can still copy the code to your project, or load it with iframe. 

> ReferenceError: window is not defined

you should load it on a web browser.
